### ISSUE TITLE
Wrong dimension s/h

### ISSUE THREAD

**Issue by bbwouters** [Loic74650/PoolMaster#24]
{"pHPumpFR":1.5}                 -> call this command to set pH pump flow rate un L/s. In this example 1.5L/s
  {"ChlPumpFR":3}                  -> call this command to set Chl pump flow rate un L/s. In this example 3L/s

needs to be L/h no?

**Comment by Loic74650** [comment]
Ah yes, thx, corrected it

 

De : bbwouters <notifications@github.com> 
Envoyé : jeudi 18 juin 2020 10:36
À : Loic74650/PoolMaster <PoolMaster@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [Loic74650/PoolMaster] Wrong dimension s/h (#24)

 

{"pHPumpFR":1.5} -> call this command to set pH pump flow rate un L/s. In this example 1.5L/s
{"ChlPumpFR":3} -> call this command to set Chl pump flow rate un L/s. In this example 3L/s

needs to be L/h no?
