### ISSUE TITLE
arduino-queue does not free memory

### ISSUE THREAD

**Issue by Faexa** [Loic74650/PoolMaster#26]
Hi, 
I'm building my own script step by step, learning arduino by the way and C programming, using (all) parts of yours.
I noticed that the arduino queue you're using (https://github.com/sdesalas/Arduino-Queue.h) does not free memory when queue is emptying.
If I spam the queue to the max with MQTT commands, it will eat memory up to (max number of items queued) * (MQTTClient packet size, which is 128bits by default) (so with your settings 1k), and will never release these allocation when emptying.
I tried this arduino-queue (https://github.com/EinarArnason/ArduinoQueue) which behave differently and release the allocations. I get the same free RAM when the queue is empty that I had before spaming the queue.

It's a corner case, I doubt we would spam ourselves with MQTT commands...

Thanks for you good job with this script ! Really like it :)

**Comment by Loic74650** [comment]
Thank you Faexa,

This is not really a bug but rather a poor RAM management from the current queue library in conjunction with my code using the String class which also does a poor job at managing RAM...  The String objects holding the command payloads are allocated and never released by the queue class, as you noted. Then the String objects can only grow in size with longer commands coming in, and never decrease in size even with smaller commands coming in, leading to what you saw.

So in the development branch of the project (version 5.0.0 coming up) I have replaced the current queue library with the one you found, which does a much better job, thank you!
