### ISSUE TITLE
Nextion variable update missing

### ISSUE THREAD

**Issue by Gixy31** [Loic74650/PoolMaster#27]
When updating Filtration Start/Stop hours, the page0.vaStaSto.txt should be set with the new string in order to force updating of the field on all pages.
add this line after line #154:
myNex.writeStr(F("page0.vaStaSto.txt"), temp);

**Comment by Loic74650** [comment]
Thanks Gixy31, I believe I fixed that issue in my December 1st update of the develop branch, kindly confirm

**Comment by Gixy31** [comment]
You're right! I was using the master branch.
Another fix in your pump library: on many relay boards, the relays are activated when pulling the input LOW ; to cope with that, you must not only invert the PUMP_ON, PUMP_OFF, INTERLOCK_OK and INTERLOCK_NOK constants, but you must also change the _isrunning_  and _Interlock_ functions like this:
return (digitalRead(isrunningsensorpin) == PUMP_ON);
return (digitalRead(interlockpin) == PUMP_ON);
And for the addtionnal relays commands, the digitalWrite instructions should also be inverted in the ProcessCommand() function.
All the best,
Denis

**Comment by Loic74650** [comment]
Pump library: yes, nice catch
I think however that:

return (digitalRead(interlockpin) == PUMP_ON);

should be:

return (digitalRead(interlockpin) == INTERLOCK_OK);

**Comment by Gixy31** [comment]
Exact, copiė collé malheureuxLe 1 janv. 2021 20:36, Loic74650 <notifications@github.com> a écrit :
Pump library: yes, nice catch
I think however that:
return (digitalRead(interlockpin) == PUMP_ON);
should be:
return (digitalRead(interlockpin) == INTERLOCK_OK);
