### ISSUE TITLE
Injection question 

### ISSUE THREAD

**Issue by coreyfournier** [Loic74650/PoolMaster#30]
Do the peristolic pumps require a specific pressure, or are you injecting it on the suction side?

I'm looking to do the same thing, but my pump at a high speed will be around 20psi.

**Comment by Loic74650** [comment]
The injection schematic is available here: https://github.com/Loic74650/PoolMaster/blob/master/docs/Plumbing.png
Plkease do not post questions in this section, this is dedicated to issues and bugs only. Better to use the forum here, thank you: https://forum.arduino.cc/c/international/francais/realisations-et-projets-finis/124
